create table book (
      id bigint generated by default as identity (start with 1)
    , title varchar(255)
    , author varchar(255)
    , synopsis varchar(500)
    , format varchar (30)
    , cover blob
    , primary key (id)
);
insert into book(id, title, author, synopsis, format) values (default, 'Mostly Harmless', 'Douglas Adams', 'Douglas Adams is back with the amazing, logic-defying, but-why-stop-now fifth novel in the Hitchhiker Trilogy. Here is the epic story of Random, who sets out on a transgalactic quest to find the planet of her ancestors. Line drawings.', 'ELECTRONIC');
insert into book(id, title, author, synopsis, format) values (default, 'Sirens of Titan', 'Kurt Vonnegut', 'The Sirens of Titan is an outrageous romp through space, time, and morality. The richest, most depraved man on Earth, Malachi Constant, is offered a chance to take a space journey to distant worlds with a beautiful woman at his side. Of course there is a catch to the invitation and a prophetic vision about the purpose of human life that only Vonnegut has the courage to tell.', 'HARD_COVER');
insert into book(id, title, author, synopsis, format) values (default, 'Mother night', 'Kurt Vonnegut', 'Mother Night is a daring challenge to our moral sense. American Howard W. Campbell, Jr., a spy during World War II, is now on trial in Israel as a Nazi war criminal. But is he really guilty? In this brilliant book rife with true gallows humor, Vonnegut turns black and white into a chilling shade of gray with a verdict that will haunt us all.', 'SOFT_COVER');
